backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: chrishannaby
    api_key: 757571847277727

collections:
  - name: 'categories'
    label: 'Categories'
    label_singular: 'Category'
    folder: 'content/categories'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - { label: 'Icon', name: 'icon', widget: 'image', allow_multiple: false }
  - name: 'subcategories'
    label: 'Subcategories'
    label_singular: 'Subcategory'
    folder: 'content/subcategories'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'categories',
          search_fields: ['name'],
          value_field: '{{slug}}',
          display_fields: ['name'],
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
  - name: 'products'
    label: 'Products'
    label_singular: 'Product'
    folder: 'content/products'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'ID', name: 'id', widget: 'string' }
      - {
          label: 'Subcategory',
          name: 'subcategory',
          widget: 'relation',
          collection: 'subcategories',
          search_fields: ['name'],
          value_field: '{{slug}}',
          display_fields: ['{{category}} {{name}}'],
        }
      - {
          label: 'Price',
          name: 'price',
          widget: 'number',
          value_type: 'float',
          min: 0.01,
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
